version: '3.8'

# Versão previa, deve ser adiciona volume e mais configurações para o MongoDB
# Apenas para teste e conexão com a API 

# ===========

# Proximos containers a serem adicionados:
# - API
# - Frontend

# Dessa forma toda aplicação pode ser iniciada com apenas um comando: docker-compose up -d

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./src/backend/artigos
    container_name: artigos-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/publicaifsc?authSource=admin
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./src/frontend
    container_name: artigos-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongodb_data:  