spring.application.name=artigos

# Porta da API
server.port=8080

# endpoint padrão
server.servlet.context-path=/api/v1

# Configurações de rotas invalidas
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


# configurações do banco de dados
# Essa configuração é basica e pode ser alterada de acordo com a necessidade do projeto
# é possivel adicionar mais propriedades de configuração do banco de dados, como pool de conexões, timeout, etc.
spring.mongodb.uri=mongodb://admin:admin123@127.0.0.1:27017/publicaifsc?authSource=admin