name: CI

on:
  pull_request:
    branches:
      - main
      - 'entrega-*'

permissions:
  contents: read

jobs:
  documentos:
    name: Documentos obrigatórios
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Conferir documentos obrigatórios
        run: ls README.md USO-IA.md docs/inception.md docs/dod.md

  links:
    name: Links internos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Conferir links dos arquivos Markdown
        uses: lycheeverse/lychee-action@v2
        with:
          args: --offline --no-progress './**/*.md'

  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rodar markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: |
            **/*.md
            #avaliacao


#testes backend

  backend-tests:
    name: Backend (Spring Boot + Gradle)
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Permissão de execução no Gradle Wrapper
        run: chmod +x backend/artigos/gradlew

      - name: Rodar Testes de Unidade
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb
        run: |
          cd backend
          ./gradlew test